### ISSUE TITLE
TypeError: _pagerRef$current.setPage is not a function

### ISSUE THREAD

**Issue by chesovnik** [satya164/react-native-tab-view#1167] opened 2021-04-07 16:09 UTC
### Current behaviour

App crashes when current.setPage calls inside Pager.native.tsx

### Expected behaviour

ExceptionsManager.js:44 TypeError: _pagerRef$current.setPage is not a function

This error is located at:
    in Pager (at TabView.tsx:79)
    in RCTView (at TabView.tsx:78)
    in TabView (at SignInEnter.js:86)
    in RCTView (at KeyboardAvoidingView.js:207)
    in KeyboardAvoidingView (at SignInEnter.js:85)
    in RCTSafeAreaView (at SafeAreaView.js:55)
    in SafeAreaView (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(SafeAreaView))
    in Styled(SafeAreaView) (at SafeAreaBackground.js:29)
    in RCTView (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(RCTView))
    in Styled(RCTView) (at SafeAreaBackground.js:13)
    in SafeAreaBackground (at SignInEnter.js:84)

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

 "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-pager-view": "^5.0.12",
    "react-native-tab-view": "^3.0.1",

**Comment by MlaskyLittleBird** [comment] 2021-05-13 20:44
This is caused by using versions of react-native prior to 0.62.  Direct Manipulation of animated components requires a call to getNode() on the ref.current property.  I've attempted to create a pull request for this issue but unfortunately I get all sorts of linting errors when the pre-commit hook runs yarn lint (and I don't have time to debug it generally).

The only changes that need to be made are in Pager.native.tsx, any call to pagerRef.current.setPage can be replaced with:

`
      if (typeof pagerRef.current?.setPage !== 'function' && typeof pagerRef.current?.getNode === 'function') {      
        pagerRef.current?.getNode().setPage(index);
      }
      else {
        pagerRef.current?.setPage(index);
      }
`

There are two instances, one in jumpTo and one in the useEffect hook.

Any chance of getting a change like this merged so it works properly with ancient versions of react-native?  The only downside is that getNode will eventually be deprecated and removed.  But at least for the time being it'd let people who are stuck with older react-native versions to use the library.

**Comment by satya164** [comment] 2021-07-29 13:37
Yea, React Native 0.61.5 is very old. We don't support it.

**Closed by satya164** 2021-07-29 13:37 UTC
Labels: bug, needs repro
