### ISSUE TITLE
Tab View with Form issue

### ISSUE THREAD

**Issue by KalAvroniev** [satya164/react-native-tab-view#1177] opened 2021-05-07 07:18 UTC
I have a tab view that has KeyboardAvoidingView with padding behavour and a ScrollView child.
Inside the ScrollView I have a TextInput.

When I tap on the input to get the keyboard to type something I can see the keyboard starts showing and then quickly disappears, making anyone unable to type.

I've observed this only on version 3.0.1, 3.0.0 was too buggy to use with tab views jumping all over the place.
Going back to 2.16.0 fixes the issue.

- react-native: 0.64.1
- react-native-tab-view: 2.16.0
- react-native-pager-view: 5.1.7

**Comment by HessiPard** [comment] 2021-05-18 16:09
have this problem too

**Comment by jahanzaibbaloch99** [comment] 2021-05-19 10:48
I am having same issue whenever i click on the Textinput. the first time OnFocus event get fired but immediately after OnFocus onBlurred event Get fired automatically and my keyboard get dismissed.

**Comment by moh3n9595** [comment] 2021-05-30 19:17
Same issue only ios

**Comment by gabrielbezerra81** [comment] 2021-05-31 19:14
I have the same issue only in iOS too. Did you guys resolved?

**Comment by vrg-success** [comment] 2021-07-01 09:29
Same problem

**Comment by satya164** [comment] 2021-07-29 13:23
Duplicate of #1054

**Closed by satya164** 2021-07-29 13:23 UTC
