### ISSUE TITLE
Android: scenes get out behind TabView container

### ISSUE THREAD

**Issue by pturchik** [satya164/react-native-tab-view#1110] opened 2020-12-25 17:24 UTC
### Current behaviour

Scenes get out behind TabView container

### Expected behaviour

Should be visible only 1 tab at time.

### Code sample

Example from quick start - https://github.com/satya164/react-native-tab-view#quick-start

### Screenshots (if applicable)

left devices on the screen is ios - all good, and on the right is android - second scene is visible

![image](https://user-images.githubusercontent.com/53335451/103139563-9c195a00-46ee-11eb-9322-756223f242b2.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| expo                         | react-native-web 0.14.4
| react-native                 | 0.63.4
| react-native-tab-view        | 2.15.2
| react-native-gesture-handler | 1.9.0
| react-native-reanimated      | 1.13.2
| node                         | 15.2.1
| npm or yarn                  | yarn 1.22.10

**Comment by zgmf2000** [comment] 2021-01-06 09:18
I ran into the same issue, too. It turns out that it happened in [2.13.0](https://github.com/satya164/react-native-tab-view/compare/v2.12.0...v2.13.0). The culprit seems to be caused by the change in **TabView.tsx** which wraps the Pager in GestureHandlerWrapper.

I wrapped the TabView inside a View with the same style, and this issue is resolved.

```
    <View style={{ flex: 1, overflow: 'hidden' }}>
      <TabView />
    </View>
```

Hope this helps.

**Comment by pturchik** [comment] 2021-01-14 13:56
> I ran into the same issue, too. It turns out that it happened in [2.13.0](https://github.com/satya164/react-native-tab-view/compare/v2.12.0...v2.13.0). The culprit seems to be caused by the change in **TabView.tsx** which wraps the Pager in GestureHandlerWrapper.
> 
> I wrapped the TabView inside a View with the same style, and this issue is resolved.
> 
> ```
>     <View style={{ flex: 1, overflow: 'hidden' }}>
>       <TabView />
>     </View>
> ```
> 
> Hope this helps.

I did it, but I want it to work correctly by default from library.

**Comment by satya164** [comment] 2021-07-29 13:22
Closing since overflow is hidden by default in latest version.

**Closed by satya164** 2021-07-29 13:22 UTC
Labels: bug
