### ISSUE TITLE
Switching between portrait and landscape orientation UI stucks between two tabs

### ISSUE THREAD

**Issue by Thebarda** [satya164/react-native-tab-view#877] opened 2019-09-09 14:50 UTC
### Current behaviour

Especially on scrollable tab, when i'm switching between vertical and horizontal device orientation, UI stucks between two tabs but it could be unblocked by a swipe or a press on a tab item

### Expected behaviour

when i'm switching between vertical and horizontal device orientation, UI should stay at same tab 

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

There is a repro in [example](https://github.com/react-native-community/react-native-tab-view/tree/master/example) folder

### Screenshots (if applicable)

![Screenrecorder-2019-09-09-16-41-17-382](https://user-images.githubusercontent.com/12515407/64541277-e3c17a00-d321-11e9-9c5d-cc08297774b7.gif)
Sorry for bad quality :/

### What have you tried

Nothing for the moment

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 28
| react-native                 | 0.59.8 (same bug with 0.60.4)
| react-native-tab-view        | 
| react-native-gesture-handler | 1.2.1
| react-native-reanimated      | 1.0.1
| node                         | 10.15.2
| npm                  | 6.9.0

**Comment by deefourple** [comment] 2019-09-26 22:21
@Thebarda Any luck on resolving this? I'm getting the same issue for both Android & iOS.

**Comment by Thebarda** [comment] 2019-09-26 22:33
@deefourple Sorry but I'm in vacation until next week. I'll keep you in touch

**Comment by wayne214** [comment] 2019-10-22 10:21
sorry, the problem still exists

**Comment by Thebarda** [comment] 2019-10-24 14:28
@wayne214 I've just create another PR

**Comment by truongnv91** [comment] 2019-11-04 07:23
Same error

**Comment by osdnk** [comment] 2019-11-04 22:41
I made some hack in order to make it workable. Idk if it helps your cases #915

**Comment by jsamr** [comment] 2019-12-05 10:13
@satya164 @osdnk I've had multiple users reporting this issue, mainly on iOS, with version 2.10.2... I think you can reopen.

**Comment by Pipo93** [comment] 2020-02-04 09:21
The problem still exists with current version (2.13.0) in our case... Should be reopened since the fix of #915 was reverted in November

**Comment by karmil32** [comment] 2020-03-23 08:18
any update? i still facing this issue ...

**Comment by Jarkendar** [comment] 2020-03-24 07:42
The problem still exists.

**Comment by rubita-svmx** [comment] 2020-10-29 12:10
I have the same problem but only in ios.

**Comment by alvaro1728** [comment] 2021-02-26 20:07
Same problem.  It happens when I'm on one of the inner tabs and I switch from portrait to landscape or viceversa.  It's happening on both iOS and Android for me.

**Comment by alvaro1728** [comment] 2021-02-27 08:10
Found a workaround by forcing the component to refresh itself when the orientation changes. 

    const window = Dimensions.get("window");

    return (
      <Tab.Navigator
        key={window.width}  
        ...

Cheers,
Alvaro

**Comment by Knight704** [comment] 2021-03-23 15:10
The problem is also present in @react-navigation/material-top-tabs since it is based on react-native-tab-view

Any suggestion on that please?

**Comment by alvaro1728** [comment] 2021-03-24 04:20
Updating `react-native-tab-view` to the latest version (3.0.0) solved this for me.

**Comment by satya164** [comment] 2021-07-29 11:51
Closing since this should be fixed in latest version.

**Closed by satya164** 2021-07-29 11:51 UTC
Labels: bug, hacktoberfest, help wanted

**Comment by summer-wu** [comment] 2022-10-18 08:45
I've tested, these two combination works fine.
```
"react-native-pager-view": "5.4.25
"react-native-tab-view": "3.3.0"
```
And these two combination works bad as the poster says:
```
"react-native-pager-view": "5.4.14"
"react-native-tab-view": "3.3.0"
```
