### ISSUE TITLE
Embedding react-native-tab-view in scrollview is not working

### ISSUE THREAD

**Issue by yasodha-r** [satya164/react-native-tab-view#1274] opened 2021-10-08 07:33 UTC
### Current behavior

It perfectly works fine with non scrollable views. But when it is wrapped inside Scrollview, tabview route contents disappearing.  But it is already mentioned in Readme as - 'Avoid rendering TabView inside ScrollView' and 'So avoid doing it if possible'. My question is it possible to wrap it in Scrollview like this,

`<ScrollView style={styles.scrollView}>
      <View style={{flex: 1}}>
 <TabView
          renderTabBar={renderTabBar}
          navigationState={{index, routes}}
          renderScene={renderScene}
          onIndexChange={setIndex}
          initialLayout={initialLayout}/>
 </View>
 </ScrollView>
`

### Expected behavior

To be able to run inside Scrollview

### Reproduction

https://snack.expo.dev/kv0RZ0qCK

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.6
| react-native                           |0.64.2
| expo                                   | NA
| node                                   | v12.22.1
| npm or yarn                            | 7.19.1

**Comment by timi-codes** [comment] 2021-10-11 21:06
@TeyimPila Thanks, man. This works like magic

**Comment by jamesisaac** [comment] 2021-12-23 13:46
Related issues and PRs (aiming to fix the variable-length content use case):

#1178 
#1198 
#1237

**Comment by sergey-king** [comment] 2022-01-07 16:59
any updates on this?

**Comment by leethree** [comment] 2022-01-10 13:17
we have dynamic content inside the tabs. it was working in v2. but the height shrinks to 0 with v3.

would greatly appreciate any workaround that allows for variable-height content.

**Comment by vargajacint** [comment] 2022-03-08 20:20
Any update?

**Comment by thuantvDr4** [comment] 2022-03-22 03:12
change style ={{flex:1}} inside scrollview to contentContainerStyle={{flex:1}}

hope useful to you!

**Comment by Deepa-Palani** [comment] 2022-03-30 10:33
If anyone want to make a tabview with scrollview when there is more than three tabs please enable scroll in tabbar.it made my tabview scrollable.i have followed below code
<TabBar
      {...props}
      scrollEnabled
      indicatorStyle={styles.indicator}
      style={styles.tabbar}
      tabStyle={styles.tab}
      labelStyle={styles.label}
    />

**Comment by greenuns** [comment] 2022-04-28 08:24
> change style ={{flex:1}} inside scrollview to contentContainerStyle={{flex:1}}
> 
> hope useful to you!

this worked for me.
instead of <ScrollView style={{flex: 1}}> to
<ScrollView contentContainerStyle={{ flex: 1 }}>

tab-view version 3.1.1, React Native version 0.67.4

**Comment by sergey-king** [comment] 2022-06-09 23:32
Any update?

**Comment by IzaELK** [comment] 2022-06-23 09:51
Hello, 
I have the same issue. I want to have my tab bar and tab view in a scrollView. I have a component above my tab view. 
You can see what I want to achieve in the following diagram. 
I cannot fix the height of my scrollView because my content's length is variable.
Do you have any updates or fixes?
![goal_diagram](https://user-images.githubusercontent.com/92511839/175271218-089d27f8-78b0-4382-a1ce-c8ee86ffe563.png)

**Comment by iamemmanuel-dev** [comment] 2022-07-26 17:14
@IzaELK Please, have you found a solution to this

**Comment by turhansel** [comment] 2022-08-15 12:33
hi guys, i had the same problem. if you wrap your routes with ScrollView the problem will be solved.

``` 
const ExampleComponent = () => {
   return (
   <ScrollView>
        {content}
   <ScrollView/>
   )
}

const renderScene = SceneMap({
    first  : <ExampleComponent />,
    second : <BlaBla />
  });
```

**Comment by leethree** [comment] 2022-08-16 11:23
@turhansel the issue is about having TabView *inside* ScrollView. not the other way around.

**Comment by Gguigre** [comment] 2022-08-26 10:10
On our side we decided to use patch-package to apply those changes 

https://github.com/satya164/react-native-tab-view/pull/1237/files

until they are validated/merged

**Comment by leethree** [comment] 2022-08-26 12:32
@Gguigre I applied the patch and found that we also needed to revert a recent `react-native-pager-view` change of `childrenWithOverriddenStyle` (by removing the additional layer of `View`. see https://github.com/callstack/react-native-pager-view/commit/d22414e06c56b9c707c61f86270881185584f44e#diff-fed4d75f8ae11fb98e76134b44730daee2a90bb6ed422d0ad418755853542d40). Now it works as a temporary workaround.

**Comment by patrickschmelter** [comment] 2022-08-26 17:23
I can't seem to get it working using above pull request. I use the tab view inside a screen of react-navigation/native which forces me to use a { flex: 1 } on the contentContainerStyle of the ScrollView

**Comment by okwasniewski** [comment] 2022-09-01 11:08
Closing as it is a duplicate of #1349 which is resolved.

**Closed by okwasniewski** 2022-09-01 11:08 UTC
Labels: bug, repro provided, platform:android, platform:ios

**Comment by devunt** [comment] 2022-11-01 01:03
It is not resolved yet, the same as #1349.

**Comment by ThukuWakogi** [comment] 2022-11-12 08:06
After days of trying to find a solution, I decided to settle with [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view).

**Comment by vlkpa** [comment] 2022-11-18 08:59
Migrating [react-navigation](https://reactnavigation.org/docs/upgrading-from-5.x/) and updating react-native-tab-view from 2.16.0 to 3.3.0 causes this problem.
