### ISSUE TITLE
Got some issue when I put the tabview in <ScrollView>. 

### ISSUE THREAD

**Issue by changyu2hao** [satya164/react-native-tab-view#1037] opened 2020-06-22 17:38 UTC
The tab will not automatically change height while changing tabs, thus making some blank space in short tabs
Here are the versions I'm using:

"react-native-tab-view": "^2.14.4"
"react-native-gesture-handler": "^1.5.0"
"react-native-reanimated": "^1.4.0"

After further investigation, this issue is happening because I have 3 tabs, one of them much longer than the other two. All three tabs are the same height so the two shorter tabs with less content still scroll the full height of the longest tab's content. Any way to stop this?

EDIT: It looks like this library isn't designed to be used like this: #1019

The UI we have requires things to be scrollable before getting to this tab section in the app. Any suggestions on how to do something like this would be very helpful. pray

**Comment by kevinmcalear** [comment] 2020-06-24 18:14
@changyu2hao did you just copy and paste my comment on your first issue? lol. I'm still trying to figure this out, have you made any progress?

**Comment by GeorgeTsendra** [comment] 2020-06-26 11:55
guys, you can set in component in _renderScene in props 
`isActiveTab={this.state.index === 0} - for example`
and hide inside tab content if this tab not active 
```
render() {
    const { isActiveTab} = this.props;
    if (!isActiveTab) {
      return <View />;
    }
.......
```

**Comment by changyu2hao** [comment] 2020-06-26 20:03
> @changyu2hao did you just copy and paste my comment on your first issue? lol. I'm still trying to figure this out, have you made any progress?

No, I haven't. I give up and use another way to do my project

**Comment by kevinmcalear** [comment] 2020-06-29 11:17
Awesome! This works great. Thank you @GeorgeTsendra (& @changyu2hao for making the issue) I modified this to be used with react hooks:

to manage the required state for the tabs:
```
const [index, setIndex] = React.useState(0);
const [routes] = React.useState([
  {key: 'first', title: 'First'},
  {key: 'second', title: 'Second'},
  {key: 'third', title: 'Third'},
]);
```

to render the tabs themselves:
```
const FirstRoute = ({isActiveTab}) => {
    if (!isActiveTab) {
      return <View />;
    }
   .......
}
```

what the `renderScene` function could look like in the `TabView`:
```
<TabView
    navigationState={{index, routes}}
    renderScene={({route}) => {
        switch (route.key) {
        case 'first':
            return FirstRoute({isActiveTab: index === 0});
        case 'second':
            return SecondRoute({isActiveTab: index === 1});
        case 'third':
            return ThirdRoute({isActiveTab: index === 2});
        default:
            return null;
        }
    }}
    onIndexChange={setIndex}
    .......
/>
```

**Comment by vobear** [comment] 2021-04-13 07:50
> guys, you can set in component in _renderScene props
> `isActiveTab={this.state.index === 0} - for example`
> 
> ```
>  _renderScene = ({route}) => {
>     switch (route.key) {
>       case 'gallery':
>         return (
>           <Component
>             isActiveTab={this.state.index === 0}
>           />
>         );
> ```
> 
> and hide inside tab content if this tab not active
> 
> ```
> render() {
>     const { isActiveTab} = this.props;
>     if (!isActiveTab) {
>       return <View />;
>     }
> .......
> ```

Not the best way

**Comment by paulsjohnson91** [comment] 2021-10-01 10:32
@vobear do you know of a better solution I can try?

**Comment by okwasniewski** [comment] 2022-11-18 14:24
Closing as a duplicate of #1349

**Closed by okwasniewski** 2022-11-18 14:24 UTC
Labels: bug
