### ISSUE TITLE
keyboard hides when using useState in TextInput

### ISSUE THREAD

**Issue by Shailja1896** [satya164/react-native-tab-view#1111] opened 2020-12-31 07:47 UTC
Hi,

I am using version ^2.15.2 of react-native-tab-view. I have a text input inside the tab view in which I have used setState for updating the value of the input. 

`<TextInput style={styles.emailTextInputStyle} value={email} onChangeText={(value) => setEmail(value)} />`

Now every time I called setState on onChangeText input gets hides. Is there anything using which I can prevent the keyboard from getting close?

**Comment by Shailja1896** [comment] 2020-12-31 07:53
Here the version number for the packages:

- react-native: 0.63.3
- react-native-tab-view: 2.15.2
- react-native-gesture-handler: 1.8.0
- react-native-reanimated: 1.13.1

**Comment by brunnoandradegok** [comment] 2021-01-07 12:33
I'm having the same kind of problem!

**Comment by karventhan13** [comment] 2021-01-27 04:32
any solution

**Comment by Aliakwe** [comment] 2021-01-29 15:58
i am having the same issues anyone with a solution

**Comment by supervons** [comment] 2021-02-02 08:58
hello，everyone！
i use ref auto focus in the setState callback.
![image](https://user-images.githubusercontent.com/31637849/106576098-bfe68000-6577-11eb-952e-a19c4f8d91ef.png)

it work for me.

**Comment by nicolak** [comment] 2021-02-06 21:34
Any solution?

**Comment by Aliakwe** [comment] 2021-02-09 10:21
Hi Nicolak,

Trust you are keeping safe in this trying times. I am sorry for the late reply.

So I solved the problem using a different route.

I created each form as a separate screen and then now style the header of the screen as a tab-view or tab-bar.

When I submit the first form I store the data on the database and then the final form I get the stored data and then make a post request to the end point on submit.

Hope this helps you.

Best wishes

**Comment by asor7007** [comment] 2021-02-26 09:38
https://github.com/satya164/react-native-tab-view/issues/1054#issuecomment-774564742

Check what I wrote.

It work for me.

**Comment by Aliakwe** [comment] 2021-02-26 10:57
Thank you for you feedback

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sabarishnarain** [comment] 2021-05-01 05:12
+1 Any ETA on this issue? 
This terribly blocks me from using this library. 
The comment mentioned here [here](https://github.com/satya164/react-native-tab-view/issues/1111#issuecomment-771478081) isn't elegant since I have about 8 form inputs.

**Comment by satya164** [comment] 2021-07-29 13:24
Duplicate of #1181

**Closed by satya164** 2021-07-29 13:24 UTC
