### ISSUE TITLE
Switching between normal and bold text leads to text break

### ISSUE THREAD

**Issue by mschipperheyn** [satya164/react-native-tab-view#1004] opened 2020-05-06 16:06 UTC
### Current behaviour

When you have tabs where the default text is not regular and the active tab is bold, you can get unnecessary line breaks. I assume that this has to do with box width calculation. If the box width is  fixed and calculated on the non bold version, making it bold will lead to the box being too small.

**Start bold and set to regular when not active numerOfLines **
<img width="378" alt="Screen Shot 2020-05-06 at 12 58 53" src="https://user-images.githubusercontent.com/384959/81199880-9e7d4700-8f99-11ea-803a-f7c7c6bed419.png">

```
const styles = StyleSheet.create({
	label: {
		textAlign: 'center',
		fontSize: 14,
		fontWeight: '700',
		margin: 0,
		backgroundColor: 'transparent',
	},
});
[...]
renderLabel={({ route, focused, color }) => {
    const weight =
        focused && props.hideIcon
            ? {}
            : {
                fontWeight: '400',
                };
    return (
        <Text
            style={[
                styles.label,
                {
                    color,
                    textTransform: props.hideIcon ? 'uppercase' : undefined,
                    ...weight,
                },
            ]}
            numberOfLines={1}
            allowFontScaling
        >
            {route.options.tabBarLabel}
        </Text>
    );
}}
```
**Start bold and set to regular when not active **
<img width="378" alt="Screen Shot 2020-05-06 at 12 50 50" src="https://user-images.githubusercontent.com/384959/81199934-afc65380-8f99-11ea-9836-a0d9c8748640.png">

```
const styles = StyleSheet.create({
	label: {
		textAlign: 'center',
		fontSize: 14,
		fontWeight: '700',
		margin: 0,
		backgroundColor: 'transparent',
	},
});
[...]
renderLabel={({ route, focused, color }) => {
    const weight =
        focused && props.hideIcon
            ? {}
            : {
                fontWeight: '400',
                };
    return (
        <Text
            style={[
                styles.label,
                {
                    color,
                    textTransform: props.hideIcon ? 'uppercase' : undefined,
                    ...weight,
                },
            ]}
            allowFontScaling
        >
            {route.options.tabBarLabel}
        </Text>
    );
}}
```
** Make everything bold **
<img width="376" alt="Screen Shot 2020-05-06 at 12 51 14" src="https://user-images.githubusercontent.com/384959/81199993-c40a5080-8f99-11ea-9d2a-1864ee743aee.png">

```
const styles = StyleSheet.create({
	label: {
		textAlign: 'center',
		fontSize: 14,
		fontWeight: '700',
		margin: 0,
		backgroundColor: 'transparent',
	},
});
[...]
renderLabel={({ route, focused, color }) => {
    return (
        <Text
            style={[
                styles.label,
                {
                    color,
                    textTransform: props.hideIcon ? 'uppercase' : undefined,
                },
            ]}
            allowFontScaling
        >
            {route.options.tabBarLabel}
        </Text>
    );
}}
```
### Expected behaviour

There should be normal display if there is enough space

### Code sample

See above.

### Screenshots (if applicable)

See above

### What have you tried

- start regular and go bold
- start bold and go regular
- wrap with view 

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | Android
| react-native                 | 61.4
| react-native-tab-view        | 2.13.0, 2.14.0
| react-native-gesture-handler | 1.6.1
| react-native-reanimated      | 1.8.0
| node                         | 12.16.4
| npm or yarn                  | yarn

**Comment by thanhluantl2304** [comment] 2020-05-19 06:58
I faced the same, anybody has solution for that?

**Comment by tcK1** [comment] 2020-07-06 22:11
Also facing the same behavior.

**Comment by GleidsonDaniel** [comment] 2020-07-07 14:01
The dumb solution to this problem is to put a space after the text. 💩 
Original: `{key: 'home', title: 'Home'}`
Solution: `{key: 'home', title: 'Home '}`
Not the best thing, but here it worked 👌

**Comment by adakerja-ali2** [comment] 2020-07-08 12:06
> The dumb solution to this problem is to put a space after the text. 💩
> Original: `{key: 'home', title: 'Home'}`
> Solution: `{key: 'home', title: 'Home '}`
> Not the best thing, but here it worked 👌

seems it depends on text length sometime you have to add 2 space LOL

**Comment by hengkx** [comment] 2020-09-18 00:57
Can you tell me when it can be solved? Thanks.

**Comment by GleidsonDaniel** [comment] 2020-10-26 17:55
This solution I posted earlier works on some devices, on others it doesn't.
So I found a better solution, leaving the bold text rendered on the screen from the start, along with the main text, however transparent and with a small size.
The problem I see is that the lib does not render again when changing the font size, which causes a mismatch with the layout, some memoization or pure components.

My solution:
```
renderLabel={({route, focused}) => {
  return (
    <View>
      <Text style={{fontWeight: focused ? 'bold' : 'normal'}}>
        {route.title}
      </Text>
      <View style={{height: 1}}>
        <Text
          style={{
            fontWeight: 'bold',
            color: 'transparent',
          }}>
          {route.title}
        </Text>
      </View>
    </View>
  );
}}
```

**Comment by satya164** [comment] 2021-07-29 12:34
Duplicate of #996 992

**Closed by satya164** 2021-07-29 12:34 UTC
Labels: bug
