### ISSUE TITLE
How to set activeTabBackgroundColor on activeTab ?

### ISSUE THREAD

**Issue by tsaohucn** [satya164/react-native-tab-view#1028] opened 2020-06-07 05:44 UTC
How to set activeTabBackgroundColor on activeTab ? Now it seems we only have activeColor prop. I want to use different style on different tab, but renderTab callback don't give me each index to separate   different tab behavior,  now I'm using renderLabel callback, but it's a bad way.

**Comment by satya164** [comment] 2021-07-29 12:44
Duplicate of #804

**Closed by satya164** 2021-07-29 12:44 UTC
Labels: feature request
