### ISSUE TITLE
Disabling animation via timingConfig breaks tab selection (requires two clicks)

### ISSUE THREAD

**Issue by SilentChris** [satya164/react-native-tab-view#967] opened 2020-02-18 19:18 UTC
### Current behaviour

I disabled animation between tabs using the `timingConfig` property of `TabView`. However, after doing so, when selecting a tab, the content changes appropriately but the tab itself isn't highlighted until I click again (on the same or a different tab).

### Expected behaviour

The tab highlight updates along with the content when animation is disabled.

### Screenshots (if applicable)

![rntabview-animation-bug](https://user-images.githubusercontent.com/71007/74769879-085e3e00-5240-11ea-96e9-0871a31f7b68.gif)

### What have you tried

Tried upgrading `react-native-gesture-handler` and `react-native-reanimated` but neither fixed the issue.
No known workarounds

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| react-native                 | 0.61.5
| react-native-tab-view        | 2.13.0
| react-native-gesture-handler | 1.5.0 (upgraded to 1.6.0)
| react-native-reanimated      | 1.3.2 (upgraded to 1.7.0)
| node                         | 11.12.0
| npm or yarn                  | 6.7.0

**Comment by CDBridger** [comment] 2020-03-02 20:37
yeah I get the same issue, is there another way of disabling the animation? (I'm using this library through react navigation)

**Comment by raarts** [comment] 2020-05-02 08:01
I use 2.14.0, and experienced the problem when setting duration to zero, BUT any other really small value fixed it for me:

```
      timingConfig={{
        duration: 1,  // milliseconds
      }}
```
Works on the web as well (where I'm using it on the first place..).

**Comment by raarts** [comment] 2020-05-02 10:02
I dug some more into this. I replaced the tabBar with my own tab bar component, and it turns out that the problem is with the animation code for the Tab Items. If I don't do any animations for the tab labels, things work out properly. 

It seems the `position` prop given to the tab bar component is broken when the `timingConfig` prop is supplied. I don't know enough about animations to dig any deeper right now, but this might help.

**Comment by dimbslmh** [comment] 2020-05-10 14:28
`duration: 0`, onChange `this.index` and `this.position` not triggered on first click.
`duration: 1-16`, onChange `this.position` not triggered on first click.
`duration: 17`, onChange working for both `this.index` and `this.position` , but may result in slightly off `this.position`.

Any custom pager available without animation?

**Comment by dylancom** [comment] 2020-12-01 14:52
Also if I use my own tabbar component it breaks when i use duration: 0

**Comment by cglacet** [comment] 2021-03-09 12:32
Still experiencing this, just like @dylancom it also breaks with a custom tab bar.

If I log the `state.index` and click on index 1, then index 0 I get the following: 

```
State index 1  // This is expected
State index 0  // This is also expected
// These two are not:
State index 1  
State index 1
```

**Comment by satya164** [comment] 2021-07-29 11:53
Closing since this is no longer relevant in latest version at uses `react-native-pager-view`

**Closed by satya164** 2021-07-29 11:53 UTC
Labels: bug, no-issue-activity
